# This workflow will build and deploy the Blazor Server app to Azure App Service
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Deploy Blazor Server to Azure

on:
  workflow_run:
    workflows: ["Deploy Infrastructure"]
    types:
      - completed

env:
  AZURE_WEBAPP_NAME: easywowmacro
  RESOURCE_GROUP_NAME: EasyWoWMacro-RG

jobs:
  build-and-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.branch == 'master' }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup .NET 10.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview
          
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --configuration Release
        
      - name: Test
        run: dotnet test --no-build --verbosity normal --configuration Release
        
      - name: Publish
        run: dotnet publish EasyWoWMacro.Web/EasyWoWMacro.Web.csproj -c Release -o ./publish
        
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Create deployment package
        run: |
          cd ./publish
          zip -r ../publish.zip .
        shell: bash
        
      - name: Azure CLI - Deploy to Azure Web App
        uses: azure/cli@v2
        with:
          azcliversion: 2.75.0
          inlineScript: |
            az webapp deployment source config-zip \
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} \
              --name ${{ env.AZURE_WEBAPP_NAME }} \
              --src ./publish.zip 